# -*- coding: utf-8 -*-
"""
Process data for Section 7. Output mass plot.
Needs pickle files generated by PDE solve to work.
"""
import pickle
import matplotlib as mpl

import matplotlib.pyplot as plt



mpl.rcParams['text.usetex'] = True
mpl.rcParams['font.family'] = 'lmodern'
mpl.rcParams['font.sans-serif'] = 'cm'
#
filename_md="particle_data"
with open(filename_md+'.pkl', 'rb') as f:
    all2 = pickle.load(f)
# import  PDE data
filename_pde="RIDK-2d-interact"
with open(filename_pde+'.pkl', 'rb') as f:
    all = pickle.load(f)
# import PDE data
filename_pde="RIDK-2d-interact-tau"
with open(filename_pde+'.pkl', 'rb') as f:
    all3 = pickle.load(f)

fig = plt.figure()
fig.set_figwidth(4)
fig.set_figheight(1.8)
    
plt.plot(all2["times"],all2["masses"],'k--',all["times"],all["masses"],'b',all3["times"],all3["masses"],'b:')
plt.xlabel(r'$t$')
plt.ylabel(r'mass')
plt.grid(True, which='both')
print("dashes=particles")
plt.show()

fig.savefig('masses.pdf', bbox_inches="tight")